# Note this script is used to compare the moves generated by Chessnut and Chessir for the same FEN positions. Chessnut must be installed for this script to work.

from Chessnut import Game as ChessnutGame
from Chessir_package.src.Chessir.game import Game

def compare_moves(fen_list, confirm_matches=False):

    for fen in fen_list:
        game = ChessnutGame(fen)
        cn_moves = game.get_moves()

        game = Game(fen)
        moves = game.get_moves()

        # compare moves
        matching_moves = set(cn_moves).intersection(moves)
        only_cn_moves = set(cn_moves) - set(moves)
        only_chessir_moves = set(moves) - set(cn_moves)

        if only_cn_moves or only_chessir_moves:
            print(fen)
            print("Matching moves:", matching_moves)
            print("Only in chessnut moves:", only_cn_moves)
            print("Only in chessir moves:", only_chessir_moves)
        else:
            if confirm_matches:
                print('All moves match.', fen)
                print(moves)

    print(f'Done. {len(fen_list)} positions compared.')

test_fens = [
    # Kasparov vs Topalov 1999
    'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    'rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1',
    'rnbqkbnr/ppp1pppp/3p4/8/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2',
    'rnbqkbnr/ppp1pppp/3p4/8/3PP3/8/PPP2PPP/RNBQKBNR b KQkq - 0 2',
    'rnbqkb1r/ppp1pppp/3p1n2/8/3PP3/8/PPP2PPP/RNBQKBNR w KQkq - 1 3',
    'rnbqkb1r/ppp1pppp/3p1n2/8/3PP3/2N5/PPP2PPP/R1BQKBNR b KQkq - 2 3',
    'rnbqkb1r/ppp1pp1p/3p1np1/8/3PP3/2N5/PPP2PPP/R1BQKBNR w KQkq - 0 4',
    'rnbqkb1r/ppp1pp1p/3p1np1/8/3PP3/2N1B3/PPP2PPP/R2QKBNR b KQkq - 1 4',
    'rnbqk2r/ppp1ppbp/3p1np1/8/3PP3/2N1B3/PPP2PPP/R2QKBNR w KQkq - 2 5',
    'rnbqk2r/ppp1ppbp/3p1np1/8/3PP3/2N1B3/PPPQ1PPP/R3KBNR b KQkq - 3 5',
    'rnbqk2r/pp2ppbp/2pp1np1/8/3PP3/2N1B3/PPPQ1PPP/R3KBNR w KQkq - 0 6',
    'rnbqk2r/pp2ppbp/2pp1np1/8/3PP3/2N1BP2/PPPQ2PP/R3KBNR b KQkq - 0 6',
    'rnbqk2r/p3ppbp/2pp1np1/1p6/3PP3/2N1BP2/PPPQ2PP/R3KBNR w KQkq - 0 7',
    'rnbqk2r/p3ppbp/2pp1np1/1p6/3PP3/2N1BP2/PPPQN1PP/R3KB1R b KQkq - 1 7',
    'r1bqk2r/p2nppbp/2pp1np1/1p6/3PP3/2N1BP2/PPPQN1PP/R3KB1R w KQkq - 2 8',
    'r1bqk2r/p2nppbp/2pp1npB/1p6/3PP3/2N2P2/PPPQN1PP/R3KB1R b KQkq - 3 8',
    'r1bqk2r/p2npp1p/2pp1npb/1p6/3PP3/2N2P2/PPPQN1PP/R3KB1R w KQkq - 0 9',
    'r1bqk2r/p2npp1p/2pp1npQ/1p6/3PP3/2N2P2/PPP1N1PP/R3KB1R b KQkq - 0 9',
    'r2qk2r/pb1npp1p/2pp1npQ/1p6/3PP3/2N2P2/PPP1N1PP/R3KB1R w KQkq - 1 10',
    'r2qk2r/pb1npp1p/2pp1npQ/1p6/3PP3/P1N2P2/1PP1N1PP/R3KB1R b KQkq - 0 10',
    'r2qk2r/pb1n1p1p/2pp1npQ/1p2p3/3PP3/P1N2P2/1PP1N1PP/R3KB1R w KQkq - 0 11',
    'r2qk2r/pb1n1p1p/2pp1npQ/1p2p3/3PP3/P1N2P2/1PP1N1PP/2KR1B1R b kq - 1 11',
    'r3k2r/pb1nqp1p/2pp1npQ/1p2p3/3PP3/P1N2P2/1PP1N1PP/2KR1B1R w kq - 2 12',
    'r3k2r/pb1nqp1p/2pp1npQ/1p2p3/3PP3/P1N2P2/1PP1N1PP/1K1R1B1R b kq - 3 12',
    'r3k2r/1b1nqp1p/p1pp1npQ/1p2p3/3PP3/P1N2P2/1PP1N1PP/1K1R1B1R w kq - 0 13',
    'r3k2r/1b1nqp1p/p1pp1npQ/1p2p3/3PP3/P1N2P2/1PP3PP/1KNR1B1R b kq - 1 13',
    '2kr3r/1b1nqp1p/p1pp1npQ/1p2p3/3PP3/P1N2P2/1PP3PP/1KNR1B1R w - - 2 14',
    '2kr3r/1b1nqp1p/p1pp1npQ/1p2p3/3PP3/PNN2P2/1PP3PP/1K1R1B1R b - - 3 14',
    '2kr3r/1b1nqp1p/p1pp1npQ/1p6/3pP3/PNN2P2/1PP3PP/1K1R1B1R w - - 0 15',
    '2kr3r/1b1nqp1p/p1pp1npQ/1p6/3RP3/PNN2P2/1PP3PP/1K3B1R b - - 0 15',
    '2kr3r/1b1nqp1p/p2p1npQ/1pp5/3RP3/PNN2P2/1PP3PP/1K3B1R w - - 0 16',
    '2kr3r/1b1nqp1p/p2p1npQ/1pp5/4P3/PNN2P2/1PP3PP/1K1R1B1R b - - 1 16',
    '2kr3r/1b2qp1p/pn1p1npQ/1pp5/4P3/PNN2P2/1PP3PP/1K1R1B1R w - - 2 17',
    '2kr3r/1b2qp1p/pn1p1npQ/1pp5/4P3/PNN2PP1/1PP4P/1K1R1B1R b - - 0 17',
    '1k1r3r/1b2qp1p/pn1p1npQ/1pp5/4P3/PNN2PP1/1PP4P/1K1R1B1R w - - 1 18',
    '1k1r3r/1b2qp1p/pn1p1npQ/Npp5/4P3/P1N2PP1/1PP4P/1K1R1B1R b - - 2 18',
    'bk1r3r/4qp1p/pn1p1npQ/Npp5/4P3/P1N2PP1/1PP4P/1K1R1B1R w - - 3 19',
    'bk1r3r/4qp1p/pn1p1npQ/Npp5/4P3/P1N2PPB/1PP4P/1K1R3R b - - 4 19',
    'bk1r3r/4qp1p/pn3npQ/Nppp4/4P3/P1N2PPB/1PP4P/1K1R3R w - - 0 20',
    'bk1r3r/4qp1p/pn3np1/Nppp4/4PQ2/P1N2PPB/1PP4P/1K1R3R b - - 1 20',
    'b2r3r/k3qp1p/pn3np1/Nppp4/4PQ2/P1N2PPB/1PP4P/1K1R3R w - - 2 21',
    'b2r3r/k3qp1p/pn3np1/Nppp4/4PQ2/P1N2PPB/1PP4P/1K1RR3 b - - 3 21',
    'b2r3r/k3qp1p/pn3np1/Npp5/3pPQ2/P1N2PPB/1PP4P/1K1RR3 w - - 0 22',
    'b2r3r/k3qp1p/pn3np1/NppN4/3pPQ2/P4PPB/1PP4P/1K1RR3 b - - 1 22',
    'b2r3r/k3qp1p/p4np1/Nppn4/3pPQ2/P4PPB/1PP4P/1K1RR3 w - - 0 23',
    'b2r3r/k3qp1p/p4np1/NppP4/3p1Q2/P4PPB/1PP4P/1K1RR3 b - - 0 23',
    'b2r3r/k4p1p/p2q1np1/NppP4/3p1Q2/P4PPB/1PP4P/1K1RR3 w - - 1 24',
    'b2r3r/k4p1p/p2q1np1/NppP4/3R1Q2/P4PPB/1PP4P/1K2R3 b - - 0 24',
    'b2r3r/k4p1p/p2q1np1/Np1P4/3p1Q2/P4PPB/1PP4P/1K2R3 w - - 0 25',
    'b2r3r/k3Rp1p/p2q1np1/Np1P4/3p1Q2/P4PPB/1PP4P/1K6 b - - 1 25',
    'b2r3r/4Rp1p/pk1q1np1/Np1P4/3p1Q2/P4PPB/1PP4P/1K6 w - - 2 26',
    'b2r3r/4Rp1p/pk1q1np1/Np1P4/3Q4/P4PPB/1PP4P/1K6 b - - 0 26',
    'b2r3r/4Rp1p/p2q1np1/kp1P4/3Q4/P4PPB/1PP4P/1K6 w - - 0 27',
    'b2r3r/4Rp1p/p2q1np1/kp1P4/1P1Q4/P4PPB/2P4P/1K6 b - - 0 27',
    'b2r3r/4Rp1p/p2q1np1/1p1P4/kP1Q4/P4PPB/2P4P/1K6 w - - 1 28',
    'b2r3r/4Rp1p/p2q1np1/1p1P4/kP6/P1Q2PPB/2P4P/1K6 b - - 2 28',
    'b2r3r/4Rp1p/p4np1/1p1q4/kP6/P1Q2PPB/2P4P/1K6 w - - 0 29',
    'b2r3r/R4p1p/p4np1/1p1q4/kP6/P1Q2PPB/2P4P/1K6 b - - 1 29',
    '3r3r/Rb3p1p/p4np1/1p1q4/kP6/P1Q2PPB/2P4P/1K6 w - - 2 30',
    '3r3r/1R3p1p/p4np1/1p1q4/kP6/P1Q2PPB/2P4P/1K6 b - - 0 30',
    '3r3r/1R3p1p/p4np1/1p6/kPq5/P1Q2PPB/2P4P/1K6 w - - 1 31',
    '3r3r/1R3p1p/p4Qp1/1p6/kPq5/P4PPB/2P4P/1K6 b - - 0 31',
    '3r3r/1R3p1p/p4Qp1/1p6/1Pq5/k4PPB/2P4P/1K6 w - - 0 32',
    '3r3r/1R3p1p/Q5p1/1p6/1Pq5/k4PPB/2P4P/1K6 b - - 0 32',
    '3r3r/1R3p1p/Q5p1/1p6/1kq5/5PPB/2P4P/1K6 w - - 0 33',
    '3r3r/1R3p1p/Q5p1/1p6/1kq5/2P2PPB/7P/1K6 b - - 0 33',
    '3r3r/1R3p1p/Q5p1/1p6/2q5/2k2PPB/7P/1K6 w - - 0 34',
    '3r3r/1R3p1p/6p1/1p6/2q5/2k2PPB/7P/QK6 b - - 1 34',
    '3r3r/1R3p1p/6p1/1p6/2q5/5PPB/3k3P/QK6 w - - 2 35',
    '3r3r/1R3p1p/6p1/1p6/2q5/5PPB/1Q1k3P/1K6 b - - 3 35',
    '3r3r/1R3p1p/6p1/1p6/2q5/5PPB/1Q5P/1K1k4 w - - 4 36',
    '3r3r/1R3p1p/6p1/1p6/2q5/5PP1/1Q5P/1K1k1B2 b - - 5 36',
    '7r/1R3p1p/6p1/1p6/2q5/5PP1/1Q1r3P/1K1k1B2 w - - 6 37',
    '7r/3R1p1p/6p1/1p6/2q5/5PP1/1Q1r3P/1K1k1B2 b - - 7 37',
    '7r/3r1p1p/6p1/1p6/2q5/5PP1/1Q5P/1K1k1B2 w - - 0 38',
    '7r/3r1p1p/6p1/1p6/2B5/5PP1/1Q5P/1K1k4 b - - 0 38',
    '7r/3r1p1p/6p1/8/2p5/5PP1/1Q5P/1K1k4 w - - 0 39',
    '7Q/3r1p1p/6p1/8/2p5/5PP1/7P/1K1k4 b - - 0 39',
    '7Q/5p1p/6p1/8/2p5/3r1PP1/7P/1K1k4 w - - 1 40',
    'Q7/5p1p/6p1/8/2p5/3r1PP1/7P/1K1k4 b - - 2 40',
    'Q7/5p1p/6p1/8/8/2pr1PP1/7P/1K1k4 w - - 0 41',
    '8/5p1p/6p1/8/Q7/2pr1PP1/7P/1K1k4 b - - 1 41',
    '8/5p1p/6p1/8/Q7/2pr1PP1/7P/1K2k3 w - - 2 42',
    '8/5p1p/6p1/8/Q4P2/2pr2P1/7P/1K2k3 b - - 0 42',
    '8/7p/6p1/5p2/Q4P2/2pr2P1/7P/1K2k3 w - - 0 43',
    '8/7p/6p1/5p2/Q4P2/2pr2P1/7P/2K1k3 b - - 1 43',
    '8/7p/6p1/5p2/Q4P2/2p3P1/3r3P/2K1k3 w - - 2 44',
    '8/Q6p/6p1/5p2/5P2/2p3P1/3r3P/2K1k3 b - - 3 44',
    # Other positions for testing
    '2b4k/2R5/pr2p1pr/2q2n2/P2bQ3/6P1/2KP3P/1N5R w - - 2 49',
    'B7/b7/8/4kp2/5Rp1/6P1/8/r5K1 w - - 0 1', 
    'rnbq1knr/1pp1b1p1/p7/2p1pp1p/1P6/2QP1P1P/P1N1P1P1/R1BK1BNR w - - 0 12', 
    '6k1/8/2KQr3/Pp4p1/6PP/3P4/3R4/5b2 w - - 2 64',
    '1k6/2R5/1B6/3NNQ2/4P3/3B3K/PPP2PPP/4R3 w - - 19 41',
    'B7/b7/8/4kp2/5Rp1/6P1/6K1/r7 b - - 1 1',
    '2b4k/2R5/pr2p1pr/2q2n2/P2bQ3/3K2P1/3P3P/1N5R b - - 3 49',
    'B7/b7/8/4kp2/5Rp1/6P1/6K1/r7 b - - 1 1',
    'r1bqr1k1/pp2ppbp/2n3p1/2pNP2n/2B3P1/3P1N1P/PPP2P2/R1BQ1RK1 b - - 0 10',
    'Q2qk1b1/8/8/8/8/8/7P/4K3 b - - 0 1',
    '8/7p/2K1k1p1/5p2/Q4P2/2pr2P1/7P/8 b - - 1 43',
    '8/7p/6p1/5p2/5P2/2pr1QP1/7P/k1K5 b - - 1 43',
    '8/7p/6p1/5p2/5P2/2pr1QP1/7P/4k1K1 b - - 1 43',
    '8/8/8/8/8/8/7p/RNk1K3 w Q - 0 1',
    'rnbqkbnr/ppp2ppp/4p3/3pP3/8/8/PPPP1PPP/RNBQKBNR w KQkq d6 0 1',
    '8/p5kp/1p6/2p5/P5P1/2n4P/r2p4/1K6 w - - 2 37',
    '8/2p5/5p2/7r/7P/3R1P2/P3R1P1/2k1K3 b - - 13 46',
    '8/8/2p2p2/7r/7P/3R1P2/P3R1P1/2k1K3 w - - 0 47',
    'r3k2r/8/8/8/8/8/8/3RKR2 b kq - 0 1',
    'r3rk2/8/8/8/8/8/8/R3K2R w KQ - 0 1',
    'r3kb1r/p1p2pp1/2p4p/3Pp3/6b1/2P5/PP1NN2P/R2QK1q1 w Qkq - 0 16',
    '1k2r3/4N3/1r1RK3/3BQPp1/2q3b1/4r3/8/8 w - g6 0 1',
    '2b1rn2/8/2k1R3/4K3/2q1B3/8/8/8 b - - 0 1',
    '7k/2R5/pr2p1pr/2q2n2/b2b4/1N2Q1P1/2KP3P/1N5R w - - 2 49',
    '8/8/7p/8/8/8/8/4K1k1 b - - 0 1',
    '8/8/7p/8/8/8/8/2k1K3 b - - 0 1',
    '4k1K1/8/8/8/8/7P/8/8 w - - 0 1',
    '2K1k3/8/8/8/8/7P/8/8 w - - 0 1',
    ]

compare_moves(test_fens, confirm_matches=False)